# THE WORLD BANK WASTE MANAGEMENT CENSUS

Analysis of  Global Waste Managment data available.

Data Source: [https://datacatalog.worldbank.org/search/dataset/0039597]

The World Bank data inventory from 2019.

## Definitions

- **iso3c** - Abbrevation of the country
- **country_name** - Name of the Country
- **gdp** - GDP of the country in Billions for the year 2019
- **composition_food_organic_waste_percent** - Percentage of organic waste generated per yer.
- **composition_glass_percent** - Percentage of glass waste 
- **composition_metal_percent** - Percentage of metal waste
- **composition_other_percent** - Percentage of all other waste
- **composition_paper_cardboard_percent** - Percentage of paper cardboard waste
- **composition_plastic_percent** - Percentage of plastic waste
- **other_information_national_agency_to_enforce_solid_waste_laws_and_regulations** - If there exists a national agency in the country to enforce the laws.
- **other_information_national_law_governing_solid_waste_management_in_the_country** - If there exists a national law for waste mangement in the country.
- **other_information_summary_of_key_solid_waste_information_made_available_to_the_public** - If the information of the waste managemnet is made available to public.
- **population_number_of_people** - Total population of the country.
- **e_waste_tons_year** - Amount of e-waste generated/year.
- **total_waste_generated** - Amount of total waste generated by the country/year


### Please make sure to install the altair library by using command
pip install altair vega_datasets

# Exploring the Dataset

In [1]:
import pandas as pd
from pathlib import Path

world_df = pd.read_csv('countrydata.csv')
world_df.shape

(217, 17)

In [2]:
world_df.columns

Index(['iso3c', 'region_id', 'country_name', 'income_id', 'gdp',
       'composition_food_organic_waste_percent', 'composition_glass_percent',
       'composition_metal_percent', 'composition_other_percent',
       'composition_paper_cardboard_percent', 'composition_plastic_percent',
       'other_information_national_agency_to_enforce_solid_waste_laws_and_regulations',
       'other_information_national_law_governing_solid_waste_management_in_the_country',
       'other_information_summary_of_key_solid_waste_information_made_available_to_the_public',
       'population_number_of_people', 'e_waste_tons_year',
       'total_waste_generated'],
      dtype='object')

In [3]:
world_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 217 entries, 0 to 216
Data columns (total 17 columns):
 #   Column                                                                                 Non-Null Count  Dtype
---  ------                                                                                 --------------  -----
 0   iso3c                                                                                  217 non-null    object
 1   region_id                                                                              217 non-null    object
 2   country_name                                                                           216 non-null    object
 3   income_id                                                                              217 non-null    object
 4   gdp                                                                                    216 non-null    float64
 5   composition_food_organic_waste_percent                                                 176 non-null    float64
 6   composition_glass_percent                                                              171 non-null    float64
 7   composition_metal_percent                                                              170 non-null    float64
 8   composition_other_percent                                                              175 non-null    float64
 9   composition_paper_cardboard_percent                                                    176 non-null    float64
 10  composition_plastic_percent                                                            175 non-null    float64
 11  other_information_national_agency_to_enforce_solid_waste_laws_and_regulations          164 non-null    object
 12  other_information_national_law_governing_solid_waste_management_in_the_country         194 non-null    object
 13  other_information_summary_of_key_solid_waste_information_made_available_to_the_public  73 non-null     object
 14  population_number_of_people                                                            217 non-null    int64
 15  e_waste_tons_year                                                                      182 non-null    float64
 16  total_waste_generated                                                                  215 non-null    float64
dtypes: float64(9), int64(1), object(7)
memory usage: 28.9+ KB

#### Checking for Null Values

In [4]:
world_df.isnull().sum().sort_values(ascending=False)

other_information_summary_of_key_solid_waste_information_made_available_to_the_public    144
other_information_national_agency_to_enforce_solid_waste_laws_and_regulations             53
composition_metal_percent                                                                 47
composition_glass_percent                                                                 46
composition_other_percent                                                                 42
composition_plastic_percent                                                               42
composition_food_organic_waste_percent                                                    41
composition_paper_cardboard_percent                                                       41
e_waste_tons_year                                                                         35
other_information_national_law_governing_solid_waste_management_in_the_country            23
total_waste_generated                                                                      2
gdp                                                                                        1
country_name                                                                               1
region_id                                                                                  0
income_id                                                                                  0
population_number_of_people                                                                0
iso3c                                                                                      0
dtype: int64

In [5]:
world_df

,iso3c,region_id,country_name,income_id,gdp,composition_food_organic_waste_percent,composition_glass_percent,composition_metal_percent,composition_other_percent,composition_paper_cardboard_percent,composition_plastic_percent,other_information_national_agency_to_enforce_solid_waste_laws_and_regulations,other_information_national_law_governing_solid_waste_management_in_the_country,other_information_summary_of_key_solid_waste_information_made_available_to_the_public,population_number_of_people,e_waste_tons_year,total_waste_generated
0,ABW,LCN,Aruba,HIC,35563.312500,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,Yes,103187,NaN,8.813202e+04
1,AFG,SAS,Afghanistan,LIC,2057.062256,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,NaN,34656032,20000.0,5.628525e+06
2,AGO,SSF,Angola,LMC,8036.690430,51.800000,6.700000,4.400000,11.500000,11.900000,13.500000,NaN,Yes,NaN,25096150,92000.0,4.213644e+06
3,ALB,ECS,Albania,UMC,13724.058590,51.400000,4.500000,4.800000,15.210000,9.900000,9.600000,Yes,Yes,No,2854191,20000.0,1.087447e+06
4,AND,ECS,Andorra,HIC,43711.800780,31.200000,8.200000,2.600000,11.600000,35.100000,11.300000,Yes,Yes,NaN,82431,NaN,4.300000e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,XKX,ECS,Kosovo,LMC,9723.561523,42.000000,6.000000,6.000000,20.000000,8.000000,11.000000,Yes,Yes,NaN,1801800,23.0,3.190000e+05
213,YEM,MEA,"Yemen, Rep.",LIC,8269.671875,65.000000,1.000000,6.000000,6.000000,7.000000,10.000000,Yes,Yes,NaN,27584212,42000.0,4.836820e+06
214,ZAF,SSF,South Africa,UMC,12666.607420,16.381655,5.200216,16.910461,45.020646,9.396918,7.090104,Yes,Yes,NaN,51729344,321000.0,1.845723e+07
215,ZMB,SSF,Zambia,LMC,3201.289307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,14264756,15000.0,2.608268e+06
216,ZWE,SSF,Zimbabwe,LIC,3190.506592,36.000000,5.000000,6.000000,3.000000,27.000000,23.000000,NaN,Yes,NaN,12500525,13000.0,1.449752e+06

## Exploring the Columns

The columns of interest for this analysis include:

- iso3c
- country_name
- gdp
- composition_food_organic_waste_percent    
- other_information_national_law_governing_solid_waste_management_in_the_country
- other_information_summary_of_key_solid_waste_information_made_available_to_the_public
- population_number_of_people
- e_waste_tons_year
- total_waste_generated


The following column will be removed from the clean data:
- other_information_national_agency_to_enforce_solid_waste_laws_and_regulations
- composition_glass_percent 
- composition_metal_percent
- composition_other_percent
- composition_paper_cardboard_percent
- composition_plastic_percent

#### Checking for percentage of food organic waste

In [6]:
world_df['composition_food_organic_waste_percent'].value_counts()

43.600000    6
30.000000    6
57.000000    5
46.000000    5
45.000000    3
            ..
35.880000    1
87.600000    1
36.700000    1
49.000000    1
16.381655    1
Name: composition_food_organic_waste_percent, Length: 135, dtype: int64

#### Checking amount of countries that come under High income, medium income, low to medium income and low income countries.

In [7]:
world_df['income_id'].value_counts()

HIC    81
UMC    56
LMC    47
LIC    33
Name: income_id, dtype: int64

In [8]:
bins = [10000000, 20000000, 30000000, 40000000, 50000000, 600000000000000000]
labels = ['<10M', '<20M', '<30M', '<40M', '<50M']
world_df['population_buckets'] = pd.cut(world_df['population_number_of_people'], bins=bins, labels=labels, right=False)
world_df['population_buckets'].value_counts().apply(lambda x: format(int(x), 'n'))

<10M    27
<50M    25
<20M    14
<30M    10
<40M     8
Name: population_buckets, dtype: object

In [9]:
world_df[world_df['total_waste_generated'] < 100000]

,iso3c,region_id,country_name,income_id,gdp,composition_food_organic_waste_percent,composition_glass_percent,composition_metal_percent,composition_other_percent,composition_paper_cardboard_percent,composition_plastic_percent,other_information_national_agency_to_enforce_solid_waste_laws_and_regulations,other_information_national_law_governing_solid_waste_management_in_the_country,other_information_summary_of_key_solid_waste_information_made_available_to_the_public,population_number_of_people,e_waste_tons_year,total_waste_generated,population_buckets
0,ABW,LCN,Aruba,HIC,35563.312500,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,Yes,103187,NaN,88132.01670,NaN
4,AND,ECS,Andorra,HIC,43711.800780,31.20,8.20,2.60,11.60,35.10,11.30,Yes,Yes,NaN,82431,NaN,43000.00000,NaN
8,ASM,EAS,American Samoa,UMC,11113.442380,19.70,3.40,7.90,25.60,26.40,12.80,Yes,NaN,NaN,55599,NaN,18989.49000,NaN
9,ATG,LCN,Antigua and Barbuda,HIC,17965.501950,46.00,7.00,7.00,12.00,15.00,13.00,Yes,Yes,No,96777,1100.00,30585.00000,NaN
24,BMU,NAC,Bermuda,HIC,80982.367190,17.00,9.00,6.00,26.00,29.00,13.00,Yes,Yes,NaN,64798,NaN,82000.00000,NaN
42,COM,SSF,Comoros,LIC,2959.540039,50.00,2.00,4.00,22.00,7.00,5.00,NaN,Yes,NaN,777424,600.00,91013.00000,NaN
46,CUW,LCN,Curacao,HIC,27503.789060,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,NaN,153822,NaN,24703.81320,NaN
47,CYM,LCN,Cayman Islands,HIC,66207.445310,10.90,3.50,6.20,11.40,31.10,11.00,Yes,Yes,NaN,59172,NaN,60000.00000,NaN
52,DMA,LCN,Dominica,UMC,11708.639650,45.00,8.00,5.00,14.00,12.00,16.00,Yes,Yes,NaN,72400,NaN,13176.00000,NaN
65,FRO,ECS,Faeroe Islands,HIC,44402.878910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,48842,NaN,61000.00000,NaN
66,FSM,EAS,"Micronesia, Fed. Sts.",LMC,3440.064209,23.83,7.07,16.73,9.32,13.30,26.17,Yes,Yes,NaN,104937,200.00,26039.57000,NaN
71,GIB,ECS,Gibraltar,HIC,43711.800780,24.57,4.42,4.37,14.38,33.65,15.86,Yes,Yes,Yes,33623,201.44,16954.00000,NaN
77,GRD,LCN,Grenada,UMC,13207.711910,27.10,3.10,2.40,36.50,13.60,16.40,Yes,Yes,NaN,105481,800.00,29536.11394,NaN
78,GRL,ECS,Greenland,HIC,43948.562500,42.80,7.10,2.00,33.40,11.40,2.40,NaN,Yes,NaN,56905,NaN,50000.00000,NaN
88,IMN,ECS,Isle of Man,HIC,44203.621090,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,Yes,80759,NaN,50551.00000,NaN
103,KIR,EAS,Kiribati,LMC,2249.768555,43.60,5.50,10.00,9.30,10.90,16.50,Yes,Yes,NaN,114395,100.00,35723.82750,NaN
104,KNA,LCN,St. Kitts and Nevis,HIC,25569.357420,27.20,8.10,8.80,12.20,20.50,23.20,Yes,Yes,Yes,54288,700.00,32892.14000,NaN
111,LCA,LCN,St. Lucia,UMC,14029.982420,45.00,7.00,5.00,11.00,10.00,22.00,Yes,Yes,Yes,177206,1600.00,77616.22800,NaN
112,LIE,ECS,Liechtenstein,HIC,45726.988280,37.60,5.00,12.50,9.10,30.30,5.40,Yes,Yes,NaN,36545,293.00,32382.00000,NaN
114,LSO,SSF,Lesotho,LMC,1978.608398,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1965662,1800.00,73457.00000,NaN
119,MAF,LCN,St. Martin (French part),HIC,30385.894530,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,30959,NaN,15479.50000,NaN
121,MCO,ECS,Monaco,HIC,43711.800780,NaN,3.00,2.20,NaN,2.20,1.00,Yes,Yes,Yes,37783,NaN,46000.00000,NaN
126,MHL,EAS,Marshall Islands,UMC,3628.895264,8.00,2.00,6.00,31.00,11.00,13.00,Yes,Yes,NaN,52793,NaN,8614.00000,NaN
133,MNP,EAS,Northern Mariana Islands,HIC,60955.726560,43.60,5.50,10.00,9.30,10.90,16.50,Yes,Yes,Yes,54036,NaN,32761.41450,NaN
147,NRU,EAS,Nauru,UMC,11167.319340,43.60,5.50,10.00,9.30,10.90,16.50,Yes,Yes,NaN,13049,NaN,6191.75050,NaN
154,PLW,EAS,Palau,HIC,18275.025390,26.00,5.00,10.00,9.00,15.00,32.00,None,Yes,Yes,21503,200.00,9426.74550,NaN
173,SMR,ECS,San Marino,HIC,58806.199220,5.35,5.61,0.90,65.56,13.21,5.60,NaN,NaN,NaN,33203,NaN,17174.68000,NaN
177,STP,SSF,São Tomé and Príncipe,LMC,3720.786865,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,191266,200.00,25586.50000,NaN
178,SUR,LCN,Suriname,UMC,16953.802730,57.00,3.00,3.00,24.00,NaN,11.00,No,No,No,526103,5000.00,78619.79915,NaN
184,SYC,SSF,Seychelles,HIC,23302.953130,48.50,5.20,4.60,25.80,5.90,9.90,Yes,Yes,Yes,88303,1100.00,48000.00000,NaN
192,TLS,EAS,Timor-Leste,LMC,3344.573730,43.60,5.50,10.00,9.30,10.90,16.50,Yes,Yes,NaN,1268671,3600.00,63875.00000,NaN
193,TON,EAS,Tonga,UMC,5636.418457,51.30,5.90,9.00,8.90,7.40,13.40,Yes,Yes,NaN,104951,300.00,17238.20175,NaN
197,TUV,EAS,Tuvalu,UMC,3793.127686,43.60,5.50,10.00,9.30,10.90,16.50,Yes,Yes,NaN,11097,10.00,3989.48650,NaN
205,VCT,LCN,St. Vincent and the Grenadines,UMC,11971.993160,49.60,5.60,3.80,10.50,22.10,8.40,Yes,Yes,Yes,109455,900.00,31561.34925,NaN
207,VGB,LCN,British Virgin Islands,HIC,24215.882810,6.50,18.10,8.60,4.80,33.50,6.30,Yes,Yes,Yes,20645,NaN,21099.19000,NaN
210,VUT,EAS,Vanuatu,LMC,3061.787354,73.40,5.40,3.80,5.70,4.05,6.45,Yes,Yes,NaN,270402,300.00,70225.48900,NaN
211,WSM,EAS,Samoa,UMC,6210.983398,42.60,2.20,8.80,19.40,7.20,13.00,Yes,Yes,Yes,187665,500.00,27399.09000,NaN

In [10]:
world_df[world_df['total_waste_generated'] > 10000000]

,iso3c,region_id,country_name,income_id,gdp,composition_food_organic_waste_percent,composition_glass_percent,composition_metal_percent,composition_other_percent,composition_paper_cardboard_percent,composition_plastic_percent,other_information_national_agency_to_enforce_solid_waste_laws_and_regulations,other_information_national_law_governing_solid_waste_management_in_the_country,other_information_summary_of_key_solid_waste_information_made_available_to_the_public,population_number_of_people,e_waste_tons_year,total_waste_generated,population_buckets
6,ARG,LCN,Argentina,HIC,23550.099610,38.740000,3.160000,1.840000,15.360000,13.960000,14.610000,NaN,Yes,NaN,42981516,291700.0,1.791055e+07,<40M
10,AUS,EAS,Australia,HIC,47784.179690,48.440000,3.810000,19.380000,3.460000,17.300000,7.610000,Yes,Yes,Yes,23789338,574000.0,1.334500e+07,<20M
17,BGD,SAS,Bangladesh,LMC,3195.737061,80.580000,0.440000,0.500000,8.590000,3.040000,4.670000,Yes,Yes,NaN,155727056,142000.0,1.477850e+07,<50M
26,BRA,LCN,Brazil,UMC,14596.246090,51.400000,2.400000,2.900000,16.700000,13.100000,13.500000,Yes,Yes,NaN,208494896,1411900.0,7.906958e+07,<50M
32,CAN,NAC,Canada,HIC,47672.078130,24.000000,6.000000,13.000000,8.000000,47.000000,3.000000,Yes,Yes,Yes,35544564,724000.0,2.510303e+07,<30M
36,CHN,EAS,China,UMC,16092.300780,61.200000,2.100000,1.100000,13.100000,9.600000,9.800000,Yes,Yes,NaN,1400050048,7211000.0,3.950814e+08,<50M
39,COD,SSF,"Congo, Dem. Rep.",LIC,1055.572998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,78736152,NaN,1.438523e+07,<50M
41,COL,LCN,Colombia,UMC,12523.006840,59.580000,2.350000,1.100000,15.740000,8.400000,12.830000,NaN,No,NaN,46406648,252200.0,1.215012e+07,<40M
50,DEU,ECS,Germany,HIC,53784.781250,30.000000,10.000000,1.400000,17.700000,24.000000,13.000000,Yes,Yes,Yes,83132800,2465085.0,5.062788e+07,<50M
55,DZA,MEA,Algeria,UMC,11826.165040,54.400000,1.200000,2.800000,0.800000,9.800000,16.900000,Yes,Yes,Yes,40606052,252000.0,1.237874e+07,<40M
57,EGY,MEA,"Egypt, Arab Rep.",LMC,10301.107420,56.000000,4.000000,2.000000,15.000000,10.000000,13.000000,Yes,No,NaN,87813256,497000.0,2.100000e+07,<50M
59,ESP,ECS,Spain,HIC,40985.558590,49.000000,8.000000,3.000000,14.000000,15.000000,9.000000,Yes,Yes,Yes,47076780,1202597.0,2.240855e+07,<40M
64,FRA,ECS,France,HIC,46110.183590,32.000000,10.000000,3.000000,26.000000,20.000000,9.000000,Yes,Yes,NaN,67059888,2218682.0,3.674882e+07,<50M
68,GBR,ECS,United Kingdom,HIC,46290.121090,16.700000,2.200000,3.500000,28.200000,18.900000,20.200000,Yes,Yes,NaN,66460344,3584126.0,3.077114e+07,<50M
87,IDN,EAS,Indonesia,LMC,10531.198240,53.800000,2.500000,1.800000,12.900000,14.900000,14.000000,Yes,Yes,NaN,261115456,1274000.0,6.520000e+07,<50M
89,IND,SAS,India,LMC,6496.807617,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,Yes,1352617344,1700000.0,1.897500e+08,<50M
91,IRN,MEA,"Iran, Islamic Rep.",UMC,14535.862300,72.900000,1.900000,2.300000,5.000000,7.300000,8.500000,Yes,Yes,No,80277424,630000.0,1.788500e+07,<50M
92,IRQ,MEA,Iraq,UMC,10310.679690,68.700000,2.300000,0.980000,6.000000,9.600000,5.290000,No,No,NaN,36115648,221000.0,1.314000e+07,<30M
95,ITA,ECS,Italy,HIC,42419.722660,34.400000,7.600000,4.300000,15.400000,22.800000,11.600000,Yes,Yes,NaN,60297396,2800026.0,3.008840e+07,<50M
98,JPN,EAS,Japan,HIC,41309.957030,36.000000,5.000000,4.000000,6.000000,33.000000,11.000000,No,Yes,NaN,126529104,518978.0,4.272000e+07,<50M
105,KOR,EAS,"Korea, Rep.",HIC,42105.281250,30.000000,2.500000,2.600000,NaN,41.000000,24.300000,Yes,Yes,NaN,51606632,570635.0,2.045278e+07,<50M
125,MEX,LCN,Mexico,UMC,19332.074220,52.400000,5.900000,3.400000,12.100000,13.800000,10.900000,NaN,Yes,NaN,125890952,957900.0,5.310000e+07,<50M
138,MYS,EAS,Malaysia,UMC,23906.265630,46.000000,3.000000,3.000000,9.000000,14.000000,15.000000,Yes,Yes,Yes,30228016,280000.0,1.298268e+07,<30M
142,NGA,SSF,Nigeria,LMC,4690.379395,NaN,3.100000,NaN,11.300000,8.000000,4.800000,NaN,Yes,NaN,154402176,277000.0,2.761483e+07,<50M
150,PAK,SAS,Pakistan,LMC,4571.414551,30.000000,6.000000,4.000000,20.000000,13.000000,9.000000,Yes,No,NaN,193203472,301000.0,3.076000e+07,<50M
153,PHL,EAS,Philippines,LMC,7705.045410,52.310000,2.340000,4.220000,21.520000,8.700000,10.550000,Yes,Yes,Yes,103320224,290000.0,1.463192e+07,<50M
156,POL,ECS,Poland,HIC,33221.542970,37.270000,10.070000,2.170000,26.690000,11.270000,12.130000,Yes,Yes,NaN,37970872,224452.0,1.275821e+07,<30M
164,RUS,ECS,Russian Federation,UMC,26012.849610,28.410000,16.820000,1.830000,19.030000,19.700000,14.210000,Yes,Yes,NaN,143201680,1392000.0,6.000000e+07,<50M
166,SAU,MEA,Saudi Arabia,HIC,48921.230470,45.500000,4.000000,5.000000,2.500000,27.000000,11.000000,Yes,yes,NaN,31557144,508000.0,1.612570e+07,<30M
189,THA,EAS,Thailand,UMC,16301.538090,65.520000,3.040000,1.850000,4.740000,7.600000,17.590000,Yes,Yes,NaN,68657600,384233.0,2.685337e+07,<50M
196,TUR,ECS,Turkey,UMC,28289.087890,64.000000,2.000000,1.000000,24.000000,6.000000,3.000000,Yes,Yes,NaN,83429616,623000.0,3.537416e+07,<50M
201,UKR,ECS,Ukraine,LMC,11534.637700,37.000000,5.000000,4.000000,22.000000,25.000000,7.000000,Yes,Yes,NaN,45004644,277000.0,1.524202e+07,<40M
203,USA,NAC,United States,HIC,61498.371090,14.900000,4.400000,9.000000,3.200000,26.600000,12.900000,Yes,Yes,Yes,326687488,2440000.0,2.652245e+08,<50M
214,ZAF,SSF,South Africa,UMC,12666.607420,16.381655,5.200216,16.910461,45.020646,9.396918,7.090104,Yes,Yes,NaN,51729344,321000.0,1.845723e+07,<50M

In [11]:
world_df[world_df['e_waste_tons_year'].isna()]

,iso3c,region_id,country_name,income_id,gdp,composition_food_organic_waste_percent,composition_glass_percent,composition_metal_percent,composition_other_percent,composition_paper_cardboard_percent,composition_plastic_percent,other_information_national_agency_to_enforce_solid_waste_laws_and_regulations,other_information_national_law_governing_solid_waste_management_in_the_country,other_information_summary_of_key_solid_waste_information_made_available_to_the_public,population_number_of_people,e_waste_tons_year,total_waste_generated,population_buckets
0,ABW,LCN,Aruba,HIC,35563.312500,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,Yes,103187,NaN,8.813202e+04,NaN
4,AND,ECS,Andorra,HIC,43711.800780,31.20,8.20,2.6,11.60,35.10,11.3,Yes,Yes,NaN,82431,NaN,4.300000e+04,NaN
8,ASM,EAS,American Samoa,UMC,11113.442380,19.70,3.40,7.9,25.60,26.40,12.8,Yes,NaN,NaN,55599,NaN,1.898949e+04,NaN
24,BMU,NAC,Bermuda,HIC,80982.367190,17.00,9.00,6.0,26.00,29.00,13.0,Yes,Yes,NaN,64798,NaN,8.200000e+04,NaN
34,CHI,ECS,Channel Islands,HIC,46672.593750,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,NaN,164541,NaN,1.789330e+05,NaN
39,COD,SSF,"Congo, Dem. Rep.",LIC,1055.572998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,78736152,NaN,1.438523e+07,<50M
40,COG,SSF,"Congo, Rep.",LMC,4899.579590,NaN,NaN,NaN,NaN,NaN,NaN,No,Yes,NaN,2648507,NaN,4.512000e+05,NaN
45,CUB,LCN,Cuba,UMC,12984.710940,68.90,4.60,1.6,3.00,12.30,9.6,No,No,Yes,11303687,NaN,2.692692e+06,<10M
46,CUW,LCN,Curacao,HIC,27503.789060,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,NaN,153822,NaN,2.470381e+04,NaN
47,CYM,LCN,Cayman Islands,HIC,66207.445310,10.90,3.50,6.2,11.40,31.10,11.0,Yes,Yes,NaN,59172,NaN,6.000000e+04,NaN
52,DMA,LCN,Dominica,UMC,11708.639650,45.00,8.00,5.0,14.00,12.00,16.0,Yes,Yes,NaN,72400,NaN,1.317600e+04,NaN
65,FRO,ECS,Faeroe Islands,HIC,44402.878910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,48842,NaN,6.100000e+04,NaN
75,GNQ,SSF,Equatorial Guinea,UMC,24827.072270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1221490,NaN,1.984431e+05,NaN
78,GRL,ECS,Greenland,HIC,43948.562500,42.80,7.10,2.0,33.40,11.40,2.4,NaN,Yes,NaN,56905,NaN,5.000000e+04,NaN
80,GUM,EAS,Guam,HIC,59074.941410,27.30,4.60,9.0,8.70,28.50,12.4,Yes,Yes,Yes,159973,NaN,1.415000e+05,NaN
88,IMN,ECS,Isle of Man,HIC,44203.621090,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,Yes,80759,NaN,5.055100e+04,NaN
109,LBR,SSF,Liberia,LIC,1333.422241,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,NaN,3512932,NaN,5.644667e+05,NaN
119,MAF,LCN,St. Martin (French part),HIC,30385.894530,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,30959,NaN,1.547950e+04,NaN
121,MCO,ECS,Monaco,HIC,43711.800780,NaN,3.00,2.2,NaN,2.20,1.0,Yes,Yes,Yes,37783,NaN,4.600000e+04,NaN
126,MHL,EAS,Marshall Islands,UMC,3628.895264,8.00,2.00,6.0,31.00,11.00,13.0,Yes,Yes,NaN,52793,NaN,8.614000e+03,NaN
133,MNP,EAS,Northern Mariana Islands,HIC,60955.726560,43.60,5.50,10.0,9.30,10.90,16.5,Yes,Yes,Yes,54036,NaN,3.276141e+04,NaN
140,NCL,EAS,New Caledonia,HIC,57330.203130,43.60,5.50,10.0,9.30,10.90,16.5,NaN,Yes,NaN,278000,NaN,1.081574e+05,NaN
147,NRU,EAS,Nauru,UMC,11167.319340,43.60,5.50,10.0,9.30,10.90,16.5,Yes,Yes,NaN,13049,NaN,6.191751e+03,NaN
160,PSE,MEA,West Bank and Gaza,LMC,5985.683105,59.10,2.40,2.7,11.50,10.10,14.2,Yes,Yes,Yes,4046901,NaN,1.387000e+06,NaN
161,PYF,EAS,French Polynesia,HIC,60955.726560,47.00,3.00,3.0,29.00,16.00,2.0,Yes,No,Yes,273528,NaN,1.470000e+05,NaN
173,SMR,ECS,San Marino,HIC,58806.199220,5.35,5.61,0.9,65.56,13.21,5.6,NaN,NaN,NaN,33203,NaN,1.717468e+04,NaN
174,SOM,SSF,Somalia,LIC,1862.614136,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14317996,NaN,2.326099e+06,<10M
176,SSD,SSF,South Sudan,LIC,1795.991943,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11177490,NaN,2.680681e+06,<10M
183,SXM,LCN,Sint Maarten (Dutch part),HIC,NaN,46.00,7.00,7.0,12.00,15.00,13.0,Yes,Yes,Yes,37685,NaN,NaN,NaN
185,SYR,MEA,Syrian Arab Republic,LIC,8587.050781,57.00,3.00,4.0,22.00,7.00,7.0,Yes,Yes,NaN,20824892,NaN,4.500000e+06,<20M
186,TCA,LCN,Turks and Caicos Islands,HIC,28174.482420,21.80,20.50,7.6,2.40,31.50,16.3,NaN,Yes,NaN,34900,NaN,NaN,NaN
190,TJK,ECS,Tajikistan,LIC,2616.475586,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,NaN,8177809,NaN,1.787400e+06,NaN
204,UZB,ECS,Uzbekistan,LMC,5164.274414,40.00,3.00,2.0,17.50,17.50,2.5,Yes,Yes,NaN,29774500,NaN,4.000000e+06,<20M
207,VGB,LCN,British Virgin Islands,HIC,24215.882810,6.50,18.10,8.6,4.80,33.50,6.3,Yes,Yes,Yes,20645,NaN,2.109919e+04,NaN
208,VIR,LCN,Virgin Islands (U.S.),HIC,30436.564450,46.00,7.00,7.0,12.00,15.00,13.0,Yes,Yes,NaN,105784,NaN,1.465000e+05,NaN

In [12]:
world_df['total_waste_generated'].describe().apply(lambda x: format(int(x), 'f'))

count          215.000000
mean       9638989.000000
std       36002157.000000
min           3989.000000
25%         213879.000000
50%        1787400.000000
75%        5282711.000000
max      395081376.000000
Name: total_waste_generated, dtype: object

In [13]:
world_df['gdp'].describe().apply(lambda x: format(int(x), 'f'))

count       216.000000
mean      22645.000000
std       22663.000000
min         822.000000
25%        4799.000000
50%       13465.000000
75%       35911.000000
max      117335.000000
Name: gdp, dtype: object

# Cleaning

#### Cleaned the data by keeping all the columns required for the analysis in a columns_to_keep dataframe and assigning it to new variable world_df

In [14]:
columns_to_keep = ['iso3c','region_id','country_name','income_id','gdp','composition_food_organic_waste_percent',
                   'composition_plastic_percent',
                   'other_information_national_law_governing_solid_waste_management_in_the_country',
                   'other_information_summary_of_key_solid_waste_information_made_available_to_the_public',
                   'population_number_of_people','e_waste_tons_year','total_waste_generated'
]

world_df = world_df[columns_to_keep]

##### Replacing the NA and None value with "No"

In [15]:
world_df['other_information_summary_of_key_solid_waste_information_made_available_to_the_public'].replace("None", pd.NA, inplace=True)
world_df['other_information_summary_of_key_solid_waste_information_made_available_to_the_public'].replace(pd.NA, "No", inplace=True)

C:\Users\Khalid Waquar\AppData\Local\Temp\ipykernel_23752\3499905995.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  world_df['other_information_summary_of_key_solid_waste_information_made_available_to_the_public'].replace("None", pd.NA, inplace=True)
C:\Users\Khalid Waquar\AppData\Local\Temp\ipykernel_23752\3499905995.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  world_df['other_information_summary_of_key_solid_waste_information_made_available_to_the_public'].replace(pd.NA, "No", inplace=True)

##### Dropping the rows with NA values in columns "composition_food_organic_waste_percent", "composition_plastic_percent", "e_waste_tons_year"

In [16]:
world_df = world_df.dropna(subset=["composition_food_organic_waste_percent", "composition_plastic_percent", "e_waste_tons_year"])

##### Replacing income_id codes with understandble Income Labels

In [17]:
world_df['income_id'].replace("HIC", 'High-Income-Country', inplace=True)
world_df['income_id'].replace("LIC", 'Low-Income-Country', inplace=True)
world_df['income_id'].replace("LMC", 'LowToMedium-Income-Country', inplace=True)
world_df['income_id'].replace("UMC", 'Medium-Income-Country', inplace=True)

world_df['other_information_national_law_governing_solid_waste_management_in_the_country'].replace("yes", 'Yes', inplace=True)

# Analyzing and Plotting

We are analyzing the amount of waste generated by the countries based on their Income levels

In [18]:
analyze_df = world_df.groupby(['income_id']).agg({'total_waste_generated':"sum"}).reset_index()
analyze_df["total_waste_generated"] = analyze_df["total_waste_generated"].astype("int64")
analyze_df.rename(columns={"income_id": "income_slab"},inplace=True)

In [19]:
import altair as alt

alt.renderers.enable("mimetype")
bars = alt.Chart(analyze_df).mark_bar().encode(
    x="income_slab",
    y="total_waste_generated",
    color=alt.Color('income_slab:N', scale=alt.Scale(scheme='category10'))
).properties(
    width=600,
    height=300
)

labels = bars.mark_text(
    align='center',
    baseline='bottom',
    dy=-5  # adjust offset to avoid overlapping with bars
).encode(
    text='total_waste_generated'
)

(bars + labels).properties(
    width=600,
    height=300
)

<VegaLite 4 object>

If you see this message, it means the renderer has not been properly enabled
for the frontend that you are using. For more information, see
https://altair-viz.github.io/user_guide/troubleshooting.html

The donut chart below describes it the data on waste managment is made available to the population of their country. You can see the data labels and the percentages if you hover over the donut chart

In [20]:
world_df['other_information_summary_of_key_solid_waste_information_made_available_to_the_public'].value_counts()

No     104
Yes     48
Name: other_information_summary_of_key_solid_waste_information_made_available_to_the_public, dtype: int64

In [21]:
# Aggregate data
analyze_df2 = world_df.groupby("other_information_summary_of_key_solid_waste_information_made_available_to_the_public")["country_name"].count().reset_index()
analyze_df2.rename(columns={"country_name": "count"}, inplace=True)

# Calculate total count
total_count = analyze_df2["count"].sum()

# Calculate percentage share
analyze_df2["share"] = analyze_df2["count"]/total_count * 100

# Create donut chart with legend
donut_chart = alt.Chart(analyze_df2, title='Donut Chart').mark_arc().encode(
    theta='count',
    color=alt.Color('other_information_summary_of_key_solid_waste_information_made_available_to_the_public', legend=alt.Legend(title='Data Available To Public?', orient='right')),
    tooltip=['other_information_summary_of_key_solid_waste_information_made_available_to_the_public', 'count', 'share']
).transform_calculate(
    end_angle='2 * PI * datum.count / {}'.format(total_count)
).transform_calculate(
    start_angle='datum.end_angle - PI * datum.count / {}'.format(total_count)
).transform_filter(
    alt.datum.count > 0
).properties(
    width=300,
    height=300
).configure_arc(
    innerRadius=70,
    strokeWidth=2
)

donut_chart

<VegaLite 4 object>

If you see this message, it means the renderer has not been properly enabled
for the frontend that you are using. For more information, see
https://altair-viz.github.io/user_guide/troubleshooting.html

Analyzing here what percentage ofcountries have a centralized governing body for their waste management in their country. Hover over the chart to see data labels

In [22]:
world_df['other_information_national_law_governing_solid_waste_management_in_the_country'].value_counts()

Yes    132
No      14
Name: other_information_national_law_governing_solid_waste_management_in_the_country, dtype: int64

In [23]:
analyze_df3 = world_df.groupby("other_information_national_law_governing_solid_waste_management_in_the_country")["country_name"].count().reset_index()
analyze_df3.rename(columns={"country_name": "count"}, inplace=True)

In [24]:
chart = alt.Chart(analyze_df3, title='Pie Chart').mark_arc().encode(
    theta='count:Q',
    color=alt.Color('other_information_national_law_governing_solid_waste_management_in_the_country:N', scale=alt.Scale(range=['#6baed6', '#fdbf6f'])),
    tooltip=['other_information_national_law_governing_solid_waste_management_in_the_country:N', 'count:Q'],  # Data labels to be displayed on hover
    text=alt.Text('count:Q', format='.2s'),  # Data labels to be displayed on the chart
).properties(
    width=400,
    height=300
)
chart

<VegaLite 4 object>

If you see this message, it means the renderer has not been properly enabled
for the frontend that you are using. For more information, see
https://altair-viz.github.io/user_guide/troubleshooting.html

Breaking down by GDP

In [25]:
world_df["gdp"].describe()

count       152.000000
mean      24379.931221
std       23138.064409
min         839.778503
25%        7311.291138
50%       16120.015135
75%       37380.665040
max      117335.585900
Name: gdp, dtype: float64

Making brackets of GPD for each country

In [26]:
def add_gpd_bracket(gdp: int):
    if gdp<10000:
        return "low_gdp"
    elif gdp<15000:
        return "medium_gdp" 
    else:
        return "high_gdp"     
world_df["gdp_bracket"] = world_df["gdp"].apply(add_gpd_bracket)

world_df[["gdp","gdp_bracket"]]

              gdp gdp_bracket
2     8036.690430     low_gdp
3    13724.058590  medium_gdp
5    67119.132810    high_gdp
6    23550.099610    high_gdp
7    11019.838870  medium_gdp
..            ...         ...
211   6210.983398     low_gdp
212   9723.561523     low_gdp
213   8269.671875     low_gdp
214  12666.607420  medium_gdp
216   3190.506592     low_gdp

[152 rows x 2 columns]

In [27]:
world_df['gdp_bracket'].value_counts()

high_gdp      79
low_gdp       48
medium_gdp    25
Name: gdp_bracket, dtype: int64

Analyzing how many of these waste managment countries has low , medium or high GDP

In [28]:
analyze_df4 = world_df.groupby("gdp_bracket")["country_name"].count().reset_index()
analyze_df4.rename(columns={"country_name": "count"}, inplace=True)

In [29]:
alt.Chart(analyze_df4).mark_bar().encode(
    x="gdp_bracket",
    y="count",
    color=alt.Color('gdp_bracket:N', scale=alt.Scale(scheme='category10'))

).properties(
    width=300,
    height=300
)

<VegaLite 4 object>

If you see this message, it means the renderer has not been properly enabled
for the frontend that you are using. For more information, see
https://altair-viz.github.io/user_guide/troubleshooting.html

In [30]:
world_df["ewaste_perc"]=(world_df['e_waste_tons_year'] * 100)/world_df['total_waste_generated']
world_df[["ewaste_perc", "e_waste_tons_year", "total_waste_generated"]]

     ewaste_perc  e_waste_tons_year  total_waste_generated
2       2.183384            92000.0           4.213644e+06
3       1.839171            20000.0           1.087447e+06
5       2.385325           134000.0           5.617682e+06
6       1.628649           291700.0           1.791055e+07
7       2.840909            14000.0           4.928000e+05
..           ...                ...                    ...
211     1.824878              500.0           2.739909e+04
212     0.007210               23.0           3.190000e+05
213     0.868339            42000.0           4.836820e+06
214     1.739156           321000.0           1.845723e+07
216     0.896705            13000.0           1.449752e+06

[152 rows x 3 columns]

In [31]:
world_df["waste_per_person_in_lbs"] = (world_df['total_waste_generated']/world_df['population_number_of_people'])*2204
world_df[["country_name","waste_per_person_in_lbs"]]

             country_name  waste_per_person_in_lbs
2                  Angola               370.051600
3                 Albania               839.723984
5    United Arab Emirates              1267.216046
6               Argentina               918.414609
7                 Armenia               373.726421
..                    ...                      ...
211                 Samoa               321.784000
212                Kosovo               390.207570
213           Yemen, Rep.               386.465681
214          South Africa               786.395809
216              Zimbabwe               255.609537

[152 rows x 2 columns]

In [32]:
top_10 = world_df.nlargest(10, "waste_per_person_in_lbs")[["country_name", "waste_per_person_in_lbs"]]

# Build the line chart
chart = alt.Chart(top_10).mark_bar().encode(
    x='country_name:N',
    y='waste_per_person_in_lbs:Q',
    color=alt.Color('country_name:N', scale=alt.Scale(scheme='category10')),
    text=alt.Text('waste_per_person_in_lbs:Q', format='.1f')

).properties(
    title='Top Ten Countries by Waste per Person',
    width=600,
    height=400
)

chart

<VegaLite 4 object>

If you see this message, it means the renderer has not been properly enabled
for the frontend that you are using. For more information, see
https://altair-viz.github.io/user_guide/troubleshooting.html

# THE PROJECT ENDS HERE

In [33]:
world_df["waste_per_person_in_lbs"].describe()

count     152.000000
mean      826.439620
std       479.253377
min       110.966909
25%       462.771157
50%       764.141701
75%      1113.413702
max      2646.789906
Name: waste_per_person_in_lbs, dtype: float64

In [34]:
def add_wastepp_bracket(waste_per_person_in_lbs: int):
    if waste_per_person_in_lbs<500:
        return "low_waste_per_person"
    elif waste_per_person_in_lbs<1000:
        return "medium_waste_per_person" 
    else:
        return "high_waste_per_person"     
world_df["wastepp_bracket"] = world_df["waste_per_person_in_lbs"].apply(add_wastepp_bracket)

world_df[["waste_per_person_in_lbs","wastepp_bracket"]]

     waste_per_person_in_lbs          wastepp_bracket
2                 370.051600     low_waste_per_person
3                 839.723984  medium_waste_per_person
5                1267.216046    high_waste_per_person
6                 918.414609  medium_waste_per_person
7                 373.726421     low_waste_per_person
..                       ...                      ...
211               321.784000     low_waste_per_person
212               390.207570     low_waste_per_person
213               386.465681     low_waste_per_person
214               786.395809  medium_waste_per_person
216               255.609537     low_waste_per_person

[152 rows x 2 columns]

In [35]:
world_df['wastepp_bracket'].value_counts()

medium_waste_per_person    64
high_waste_per_person      45
low_waste_per_person       43
Name: wastepp_bracket, dtype: int64

In [36]:
world_df[['country_name','wastepp_bracket']].value_counts()

country_name  wastepp_bracket
Albania       medium_waste_per_person    1
Morocco       low_waste_per_person       1
Netherlands   high_waste_per_person      1
New Zealand   high_waste_per_person      1
Niger         low_waste_per_person       1
                                        ..
Grenada       medium_waste_per_person    1
Guatemala     low_waste_per_person       1
Guinea        low_waste_per_person       1
Guyana        medium_waste_per_person    1
Zimbabwe      low_waste_per_person       1
Length: 151, dtype: int64

In [37]:
# Generate data
# world_df["ewaste_perc"]=(world_df['e_waste_tons_year'] * 100)/world_df['total_waste_generated']
# data = world_df[["ewaste_perc", "e_waste_tons_year", "total_waste_generated"]]

# # Melt data to long format
# melted_data = pd.melt(data, var_name='variable', value_name='value')

# # Create chart
# # alt.Chart(data).mark_bar().encode(
# #     x=alt.X('variable:N', axis=alt.Axis(title='Variables')),
# #     y=alt.Y('value:Q', axis=alt.Axis(title='Value')),
# #     color=alt.Color('variable:N', scale=alt.Scale(scheme='category10'))
# # ).properties(
# #     width=600,
# #     height=400
# # ).configure_axis(
# #     labelFontSize=14,
# #     titleFontSize=16
# # )

# # creating a custom dataframe
# # data = pd.DataFrame([[264, 'Rohit', 'ODI'], 
# #                      [183, 'Virat', 'ODI'], 
# #                      [118, 'Rohit', 'T20'], 
# #                      [94, 'Virat', 'T20'],
# #                      [212, 'Rohit','Test'],
# #                      [254, 'Virat','Test']],
# #                      columns=['Highest Score', 'Player', 'Format'])
  
# # print(data)

# gp_chart = alt.Chart(data).mark_bar().encode(
#   alt.Column('Format'), alt.X('e_waste_tons_year'),
#   alt.Y('total_waste_generated', axis=alt.Axis(grid=False)), 
#   alt.Color('ewaste_perc'))
  
# gp_chart.display()

In [38]:
# Generate data
# world_df["ewaste_perc"]=(world_df['e_waste_tons_year'] * 100)/world_df['total_waste_generated']
# data = world_df[["ewaste_perc", "e_waste_tons_year", "total_waste_generated"]]


# gp_chart = alt.Chart(data).mark_bar().encode(
#   alt.Column('Format'), alt.X('e_waste_tons_year'),
#   alt.Y('total_waste_generated', axis=alt.Axis(grid=False)), 
#   alt.Color('ewaste_perc'))
  
# gp_chart.display()